// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// rapture.cpp
integers_matrix<by_column> CPP_empty_grid(size_t n);
extern "C" SEXP _rapture_CPP_empty_grid(SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(CPP_empty_grid(cpp11::as_cpp<cpp11::decay_t<size_t>>(n)));
  END_CPP11
}
// rapture.cpp
integers_matrix<by_column> CPP_dense_grid(doubles x, doubles y, size_t n);
extern "C" SEXP _rapture_CPP_dense_grid(SEXP x, SEXP y, SEXP n) {
  BEGIN_CPP11
    return cpp11::as_sexp(CPP_dense_grid(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<size_t>>(n)));
  END_CPP11
}
// rapture.cpp
data_frame CPP_wgs_to_tile(doubles x, doubles y, size_t z);
extern "C" SEXP _rapture_CPP_wgs_to_tile(SEXP x, SEXP y, SEXP z) {
  BEGIN_CPP11
    return cpp11::as_sexp(CPP_wgs_to_tile(cpp11::as_cpp<cpp11::decay_t<doubles>>(x), cpp11::as_cpp<cpp11::decay_t<doubles>>(y), cpp11::as_cpp<cpp11::decay_t<size_t>>(z)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_rapture_CPP_dense_grid",  (DL_FUNC) &_rapture_CPP_dense_grid,  3},
    {"_rapture_CPP_empty_grid",  (DL_FUNC) &_rapture_CPP_empty_grid,  1},
    {"_rapture_CPP_wgs_to_tile", (DL_FUNC) &_rapture_CPP_wgs_to_tile, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_rapture(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
