# Generated by cpp11: do not edit by hand

CPP_empty_grid <- function(n) {
  .Call(`_rapture_CPP_empty_grid`, n)
}

CPP_dense_grid <- function(x, y, n) {
  .Call(`_rapture_CPP_dense_grid`, x, y, n)
}

CPP_wgs_to_tile <- function(x, y, z) {
  .Call(`_rapture_CPP_wgs_to_tile`, x, y, z)
}
